/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    application
}

dependencies {
    //implementation(project(":utilities"))
}

java {
    manifest {
        attributes("Main-Class" to "ee.tepp.craftinginterpreters.lox.Lox")
    }
}

application {
    // Define the main class for the application.
    mainClass = "ee.tepp.craftinginterpreters.lox.Lox"
}
